language: node_js
services:
  - mongodb
node_js:
  - "11.6"
cache:
  directories:
  - "node_modules"
env:
  global:
    - CC_TEST_REPORTER_ID=f74635e7d81d445c2d5458b4fcfe28357becbc44ce9eaeb1b0392cfe3fcb3040
    - NODE_ENV=test
    - PORT=3005
    - LOGGER_TYPE=console
    - NODE_PATH=app/src
    - CT_URL=http://mymychine:9000
    - LOCAL_URL=http://mymychine:3005
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
  - npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
