version: "3"
services:
  develop:
    build: .
    ports:
      - "3005:3005"
    container_name: node-skeleton
    env_file:
      - dev.env
    environment:
      PORT: 3005
      NODE_PATH: app/src
      CT_REGISTER_MODE: auto
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      API_VERSION: v1
    command: develop
    volumes:
      - ./app:/opt/node-skeleton/app
